server:
  port: 8090

spring:
  application:
    name: apigateway-service
  cloud:
    kubernetes:
      enabled: true
    loadbalancer:
      mode: SERVICE
    discovery:
      all-namespaces: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-performance-service
          uri: lb://employee-performance-service
          predicates:
            - Path=/api/eps/**
          filters:
            - AuthenticationFilter

        - id: employee-filter-service
          uri: lb://employee-filter-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8083

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://configserver-service:8083
