server:
  port: 8090

spring:
  application:
    name: apigateway-service
  cloud:
    kubernetes:
      enabled: true
    loadbalancer:
      mode: SERVICE
    discovery:
      all-namespaces: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-performance-service
          uri: lb://employee-performance-service
          predicates:
            - Path=/api/performance/**
          filters:
            - AuthenticationFilter

#  profiles:
#    active: dev
#
#  config:
#    import: optional:configserver:http://localhost:8083


eureka:
  client:
    enabled: false