server:
  port: 8090

spring:
  application:
    name: apigateway-service
  cloud:
    kubernetes:
      enabled: true
    loadbalancer:
      mode: SERVICE
    discovery:
      all-namespaces: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-performance-service
          uri: lb://employee-performance-service
          predicates:
            - Path=/api/eps/**
          filters:
            - AuthenticationFilter

        - id: employee-filter-service
          uri: lb://employee-filter-service
          predicates:
            - Path=/api/ef/**
          filters:
            - AuthenticationFilter

        - id: employee-project-service
          uri: lb://employee-project-service
          predicates:
            - Path=/api/ps/**
          filters:
            - AuthenticationFilter

  profiles:
    active: ${profile:prod}
